spring:
  profiles:
    active:
    - dev
    
  application:
    name: bookstore
    
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookstore1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    
  data:
    rest:
      base-path: /api
    redis:
      repositories:
        enabled: false
        
  mail:
    host: smtp.qq.com
    protocol: smtp
    username: 2864710463@qq.com
    password: zxtazjzrsbpsdeab
    default-encoding: UTF-8
    
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 5000
    
server:
  port: 9001
  
props:
  user:
    icon:
      base-path: E:\\JAVA projects\\shixi_yz\\bookstore1\\bookstore-master\\bookstore-master\\bookstore\\src\\media\\user
      url-base-path: http://127.0.0.1:9001/api/upload/user/icon/
  sale:
    icon:
      base-path: E:\\JAVA projects\\shixi_yz\\bookstore1\\bookstore-master\\bookstore-master\\bookstore\\src\\media\\sale
      url-base-path: http://127.0.0.1:9001/api/upload/sale/icon/
  rent:
    icon:
      base-path: E:\\JAVA projects\\shixi_yz\\bookstore1\\bookstore-master\\bookstore-master\\bookstore\\src\\media\\rent
      url-base-path: http://127.0.0.1:9001/api/upload/rent/icon/



---
spring:
  profiles:
  - prod
    
  application:
    name: bookstore
    
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookstore1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    
  data:
    rest:
      base-path: /api
    redis:
      repositories:
        enabled: false
        
  mail:
    host: smtp.qq.com
    protocol: smtp
    username: 2864710463@qq.com
    password: zxtazjzrsbpsdeab
    default-encoding: UTF-8
    
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 5000
    
server:
  port: 9001
  
props:
  user:
    icon:
      base-path: /home/lighthouse/projects/bookstore/media/user
      url-base-path: http://106.52.254.158:9001/api/upload/user/icon/
  sale:
    icon:
      base-path: /home/lighthouse/projects/bookstore/media/sale
      url-base-path: http://106.52.254.158:9001/api/upload/sale/icon/
  rent:
    icon:
      base-path: /home/lighthouse/projects/bookstore/media/rent
      url-base-path: http://106.52.254.158:9001/api/upload/rent/icon/